### ISSUE TITLE
Cannot install/run anything

### ISSUE THREAD

**Issue by JovannMC** [SlimeVR/slimevr-node#9]
You cannot install or run any library/application in the monorepo due to `@slimevr/common` being missing from the NPM registry.

![npx @slimevr/firmware-protocol-debugger](https://github.com/SlimeVR/slimevr-node/assets/45893380/ebb27a4f-f291-4c37-bb39-a2885f54970c)
![npm install @slimevr/firmware-protocol](https://github.com/SlimeVR/slimevr-node/assets/45893380/82f3b30b-2577-4e82-9cd4-7fa2c15c7e19)

Installing from the git repository also fails due to `workspace:*`

![npm install https://github.com/SlimeVR/slimevr-node/tree/master/packages/firmware-protocol](https://github.com/SlimeVR/slimevr-node/assets/45893380/b4b204ba-cdbf-47cf-812d-23b59601a469)

**Comment by TheDevMinerTV** [comment]
Fixed by 96b22a99bc22f14c6801a448dae2d7ee1dddcfd7.

As to why you couldn't install from git: this repository contains a PNPM workspace, which aren't supported by vanilla NPM. I recommend you to use pnpm yourself since it's install speed is vastly superior to vanilla NPM, not even mentioning the better module caching.

**Comment by Utopiah** [comment]
Is it the same problem for `npx` as mentioned in https://github.com/SlimeVR/slimevr-node/tree/master/apps/firmware-protocol-debugger ?
